# Generated by Django 4.2.1 on 2023-05-30 22:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_autor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
